version: '3'
volumes:
  WordPress:
    driver: local
    driver_opts:
      type: bind
      device: /Users/ytaya/data/WordPress
      o: bind
  DB:
    driver: local
    driver_opts:
      type: bind
      device: /Users/ytaya/data/DB
      o: bind

networks:
  Inception-network:
  
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - DB:/var/lib/mysql
    networks:
      - Inception-network
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - Inception-network
    depends_on:
      - mariadb
      - ftp
      - redis
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - WordPress:/var/www/html
    networks:
      - Inception-network
    depends_on:
      - wordpress
      - static_website
      - portainer
      - adminer
  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - Inception-network
  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    networks:
      - Inception-network
    volumes:
      - WordPress:/var/www/html
  adminer:
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - Inception-network
    depends_on:
      - mariadb
  static_website:
    build:
      context: requirements/bonus/static_website
      dockerfile: Dockerfile
    networks:
      - Inception-network
  portainer:
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    networks:
      - Inception-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock