version: '3'
volumes:
  WordPress:
  DB:
networks:
  Inception-network:
    name: Inception-network
    driver: bridge
  
services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - DB:/var/lib/mysql
    networks:
      - Inception-network
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - Inception-network
    depends_on:
      - mariadb
      - adminer
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - WordPress:/var/www/html
    networks:
      - Inception-network
    depends_on:
      - wordpress
  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - Inception-network
    depends_on:
      - wordpress
      - ftp
  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    networks:
      - Inception-network
    volumes:
      - WordPress:/var/www/html
    depends_on:
      - wordpress
  adminer:
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - Inception-network
    depends_on:
      - mariadb
